### ISSUE TITLE
DeprecationWarning triggered with numpy>=1.20

### ISSUE THREAD

**Issue by erikmannerfelt** [rock-learning/pytransform3d#114]
First of all, thanks for this great package! I use it extensively.

The type `np.float` is consistently used throughout pytransform3d. Since `numpy=1.20`, this triggers:
```
DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.                        
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

The line that triggers the warning most commonly for me is here:
https://github.com/rock-learning/pytransform3d/blob/8351d3e474ab919436fa2160c546ce72f0f7c04c/pytransform3d/transformations.py#L39

I suggest that each instance of `np.float` is replaced with either `float` or `np.float64` to avoid the warning.

**Comment by AlexanderFabisch** [comment]
Hi Erik,

> First of all, thanks for this great package! I use it extensively.

Thanks. That's good to hear. :)

And thanks for your contribution. I just merged the pull request so I will close this issue.
