### ISSUE TITLE
Release 1.9 does not contains some of the sub packages

### ISSUE THREAD

**Issue by brainoom** [rock-learning/pytransform3d#145]
This file, from pypi.org <https://files.pythonhosted.org/packages/2a/9d/1625a751df6a135bf09f033f75288db27d58bf84accd0eb36437dda09510/pytransform3d-1.9.tar.gz> is missing a lot of the code, and breaks functionality.

The reason seems to be that setup.py contains the line, ``` packages=['pytransform3d']``` that is not sufficient anymore since some of the packages are now folders and not files directly under pytransform3d. It should probably be changed to  `packages=find_packages()`, with `from setuptools import setup, find_packages` at line 2 of the setup.py file.

To see the difference, compare the result of ```python setup.py bdist_wheel```  on the current code and the same command with the proposed changed. 

I suggest removing the current release from pypi.org

Anyway, thank you very much for this great package. 

Unfortunately due to legalese I will not be able to open a PR with that change.

**Comment by AlexanderFabisch** [comment]
Thanks for the information. I will fix this as quickly as possible.

**Comment by AlexanderFabisch** [comment]
@brainoom Sorry for the inconveniences. I released 1.9.1 on PyPI, which fixes the issue. I tested it in a docker container. If you can confirm this, I we can close this issue.

**Comment by AlexanderFabisch** [comment]
Since there is no further complaint, I will close this issue. Thanks for reporting again!
