### ISSUE TITLE
SE3 clarification in docs

### ISSUE THREAD

**Issue by MitchAllain** [rock-learning/pytransform3d#175]
Thanks for sharing this work. Between the quality of your documentation and the visualization options, I think this has huge potential to educate programmers on 3D transformations.

I would suggest clarifying `The group of all rigid transformations` or distance-preserving transformations to the SE(3) documentation. I realize this is meant to be introductory, but I find the term "rigid" is most typically used to distinguish from broader affine transformations.
https://github.com/rock-learning/pytransform3d/blob/c6fb10b1d17713bd8a2d6becb928c4f6dcf611f9/doc/source/transformations.rst#L5

Also, maybe `all transformation matrices of this form generate the special Euclidean group...`, to make this more precise. Other "transformation matrices" in 3D Cartesian space can be affine, hence not SE(3).
https://github.com/rock-learning/pytransform3d/blob/c6fb10b1d17713bd8a2d6becb928c4f6dcf611f9/doc/source/transformations.rst#L74

I'm happy to submit a PR if you're comfortable with this. Also, I may follow up with a few more suggestions as I get familiar with the package. Please let me know how interested you are in further input.

**Comment by AlexanderFabisch** [comment]
Hi Mitch,

I think your suggestions are great.

> I'm happy to submit a PR if you're comfortable with this.

Sure! This makes my life easy. ;)

> Also, I may follow up with a few more suggestions as I get familiar with the package. Please let me know how interested you are in further input.

Suggestions are always welcome. The documentation could definitely benefit from a thorough review.

> Thanks for sharing this work. Between the quality of your documentation and the visualization options, I think this has huge potential to educate programmers on 3D transformations.

Thanks for your feedback! :) I was actually hoping to use it in a lecture or tutorial in the future. Let me know if you plan to use it for something similar. I'm curious.

**Comment by AlexanderFabisch** [comment]
@MitchAllain Do you still want to open a PR or should I do it?

**Comment by MitchAllain** [comment]
See #180, just the proposed updates but hope to contribute more in the future.

**Comment by AlexanderFabisch** [comment]
Thanks for the contribution!
