### ISSUE TITLE
AttributeError: 'Arrow3D' object has no attribute 'do_3d_projection' when Running Example

### ISSUE THREAD

**Issue by stanleyshly** [rock-learning/pytransform3d#176]
When running the example:  plot_camera_trajectory.py with the current stable matplotlib, I get this error: AttributeError: 'Arrow3D' object has no attribute 'do_3d_projection', but downgrading works.

**Comment by AlexanderFabisch** [comment]
Thanks for reporting. This will be fixed with #177, which will be merged into the develop branch. It might take some time to get into the PyPI package.

**Comment by stanleyshly** [comment]
I see, thank you for the response. Should I close the issue, or will you close it when it gets merged into the main branch?

**Comment by AlexanderFabisch** [comment]
Since it is in the current develop branch, I will close this issue.
