### ISSUE TITLE
Fast visualization backend

### ISSUE THREAD

**Issue by AlexanderFabisch** [rock-learning/pytransform3d#24]
Options:
* VTK - not suitable for live visualizations
* Open3D - does it support drawing lines etc.?
* pyrender - doesn't seem to be actively maintained
* pyglet - ?

**Comment by AlexanderFabisch** [comment]
It might be better to use pyglet. It has been proven to be useful in Open AI gym. Or we can use pyrender or something similar: https://github.com/mmatl/pyrender

**Comment by Jianghanxiao** [comment]
Maybe it's also worth trying open3d https://github.com/intel-isl/Open3D if this repo focuses on 3d

**Comment by AlexanderFabisch** [comment]
Didn't have a look at it since its first release. It looks really good now. Thanks for the hint.
