### ISSUE TITLE
Why not using a set?

### ISSUE THREAD

**Issue by HWiese1980** [rock-learning/pytransform3d#31]
https://github.com/rock-learning/pytransform3d/blob/153149531b6d7eec92fe688f3d9f9d955a20713a/pytransform3d/transform_manager.py#L69

Is there a reason for using a `list` and checking existence of a frame before appending, instead of using a `set` here that inherently only allows for unique items? Question is what's more efficient.

**Comment by AlexanderFabisch** [comment]
Don't know at the moment. I have to check.

**Comment by HWiese1980** [comment]
```
import time

data = "ABCDEFGHIJKLM"


t1 = time.time()
s = set()
for i in range(10000000):
    d = data[i%len(data)]
    s.add(d)
s = sorted(list(s))
print(f"Set {s} took {(time.time() - t1):.3f} seconds")

t2 = time.time()
s = []
for i in range(10000000):
    d = data[i%len(data)]
    if d not in s:
        s.append(d)
print(f"List {s} took {(time.time() - t1):.3f} seconds")
```

Results: 

```
Set ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M'] took 3.334 seconds
List ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M'] took 7.606 seconds
```

**Comment by AlexanderFabisch** [comment]
I think it has to be at least an ordered set.

**Comment by HWiese1980** [comment]
Okay, I'll do the performance check with an ordered set again

**Comment by AlexanderFabisch** [comment]
btw. why do you measure the time of `s = sorted(list(s))`?

**Comment by AlexanderFabisch** [comment]
The following operations have to be possible with the data structure of `nodes`:
* `nodes.index(frame)` - O(N) for lists
* `len(nodes)` - O(1) for lists
* `nodes[idx]` - O(1) for lists
* `name in nodes` - O(N) for lists
I don't know any other data structure that supports this although having constant time lookup would be awesome of course.

**Comment by HWiese1980** [comment]
> 
> 
> btw. why do you measure the time of `s = sorted(list(s))`?

I took that into account to have the same output in the end. But yeah... might leave that out. It doesn't cost much in such a short list.

**Comment by HWiese1980** [comment]
> 
> 
> The following operations have to be possible with the data structure of `nodes`:
> 
>     * `nodes.index(frame)` - O(N) for lists
> 
>     * `len(nodes)` - O(1) for lists
> 
>     * `nodes[idx]` - O(1) for lists
> 
>     * `name in nodes` - O(N) for lists
>       I don't know any other data structure that supports this although having constant time lookup would be awesome of course.

Does it still make things quicker to use a set and convert it to a list on demand? Depends on how often you do that. I have only seen `if xyz in nodes` be called at every `add_transform` and using a `set` for getting rid of this would speed at least this code section up.

**Comment by AlexanderFabisch** [comment]
That would be an option. Another option would be to use a dict instead of a list with the indices as values so that `nodes.index(name)` is essentially converted to `nodes[name]` and is (at least I think so) in O(1).

**Comment by HWiese1980** [comment]
I had a flaw in my calculations further up. Here's a new one:

```
import time

data = "ABCDEFGHIJKLM"


t1 = time.time()
s = set()
for i in range(10000000):
    d = data[i%len(data)]
    s.add(d)
tr = time.time()
s = sorted(list(s))
print(f"Set {s} (w/o sorting) took {(tr - t1):.3f} seconds")

t2 = time.time()
s = []
for i in range(10000000):
    d = data[i%len(data)]
    if d not in s:
        s.append(d)
tr = time.time()
print(f"List {s} took {(tr - t2):.3f} seconds")

t3 = time.time()
s = {}
for i in range(10000000):
    d = data[i%len(data)]
    if d not in s:
        s[d] = d
tr = time.time()
s = list(s.keys())
print(f"Dict Keys {s} took {(tr - t3):.3f} seconds")
```

Results:

```
Set ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M'] (w/o sorting) took 3.917 seconds
List ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M'] took 4.578 seconds
Dict Keys ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M'] took 4.079 seconds
```

A little less impressing but `set` still has the lead.

**Comment by AlexanderFabisch** [comment]
No significant advantage could be measured in #74
