### ISSUE TITLE
examples only with matplotlib version <3.1.0  compatible 

### ISSUE THREAD

**Issue by Mateus224** [rock-learning/pytransform3d#36]
The example: 
https://rock-learning.github.io/bolero/auto_examples/representation/plot_cartesian_dmp.html#sphx-glr-auto-examples-representation-plot-cartesian-dmp-py

In function:
ax = plt.subplot(221, projection="3d", aspect="equal")
NotImplementedError: It is not currently possible to manually set the aspect on 3D axes

**Comment by AlexanderFabisch** [comment]
Good catch. I've seen it before. Newer matplotlib versions changed the API. `aspect="equal"` does not work anymore. Would you like to make a pull request?

**Comment by AlexanderFabisch** [comment]
Should be moved to bolero

**Comment by AlexanderFabisch** [comment]
It is fixed with 1d452112a560ea3220d9d2465940b3f979257996 on the current master

**Comment by madratman** [comment]
Hey can you make a new release as well to port this change?

**Comment by AlexanderFabisch** [comment]
I'll release 1.1.1 as soon as possible. (Hopefully in the next 24 hours.)

**Comment by AlexanderFabisch** [comment]
It is published: https://pypi.org/project/pytransform3d/#history
