### ISSUE TITLE
Animated URDF

### ISSUE THREAD

**Issue by RomeoStaub** [rock-learning/pytransform3d#39]
Thank you for the great library!

Is it possible to animate the URDF?
If yes, could you provide an example? Much appreciated!

**Comment by AlexanderFabisch** [comment]
> Thank you for the great library!

Thanks!

> Is it possible to animate the URDF?

Matplotlib supports animations, pytransform3d supports matplotlib. So... it is possible. This is how code animations in matplotlib looks like: https://github.com/rock-learning/pytransform3d/blob/master/examples/animate_rotation.py

However, there is no convenient way to animate URDFs. Matplotlib might not be the best option for animations anyway. I would suggest to take a look at [urdfpy](https://github.com/mmatl/urdfpy) for this purpose.

**Comment by AlexanderFabisch** [comment]
I guess I can close the issue?
