### ISSUE TITLE
Quaternion SLERP fails for identical Quaternions

### ISSUE THREAD

**Issue by ruehr** [rock-learning/pytransform3d#45]
def _slerp_weights(angle, t):
    return (np.sin((1.0 - t) * angle) / np.sin(angle),
            np.sin(t * angle) / np.sin(angle))

_slerp_weights divides by 0 when the angle between the rotations to interpolate between is zero, this leads to a nan Quaternion in SLERP. It would be preferable if a SLERP between two identical rotations would always return the same rotation instead of an invalid one.

**Comment by AlexanderFabisch** [comment]
Hi @ruehr,

thanks for the hint. I will create a merge request in a minute.

**Comment by AlexanderFabisch** [comment]
Would #46 work for you?

**Comment by ruehr** [comment]
Works for me.

Indeed it works for very small values like np.nextafter(0.0,1) as an angle, so I guess it's a stable solution. My intuition would have been to test for sin(angle)!=0.0 as this is the divisor but this solution seems to be numerically stable as well for python.
I certainly don't need a warning, trying to put together a spline interpolator and there are many cases where a part of the spline could stay within a constant orientation. It's not an abnormal case so I wouldn't expect a warning.

**Comment by AlexanderFabisch** [comment]
> It's not an abnormal case so I wouldn't expect a warning.

OK, merged to master.

> I certainly don't need a warning, trying to put together a spline interpolator

I'm just curious. Is there a chance that it will be open source?
