### ISSUE TITLE
Angle between similar Quaternions sometimes nan

### ISSUE THREAD

**Issue by ruehr** [rock-learning/pytransform3d#47]
Ran into a weird issue of dot product of checked/normalized quaternions becoming >1. Didn't have time to look deeper into it, maybe after the weekend. 
```python
import pytransform3d.rotations as pr

a = ((0.9689124217106448 , 0.24740395925452294 , 0.0 , 0.0))
b = ((0.9689124217106448 , 0.247403959254523 , 0.0 , 0.0))
a = pr.check_quaternion(a)
b = pr.check_quaternion(b)

print("dot:" , np.dot(a,b))
print("divisor:", np.linalg.norm(a)*np.linalg.norm(a))
print("angle between quaternions:", pr.angle_between_vectors(a,b))
```

>dot: 1.0000000000000002
>divisor: 1.0
>angle between quaternions: nan

**Comment by AlexanderFabisch** [comment]
Thanks for reporting. I'll have a look. Seems really strange. The selected implementation is

```python
def angle_between_vectors(a, b, fast=False):
    return np.arccos(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)))
```

Of course the argument should be in [-1, 1]. I wonder if clipping is the best option.

**Comment by AlexanderFabisch** [comment]
#48 should fix this. I think there is no better and readable solution to this problem.

**Comment by AlexanderFabisch** [comment]
@ruehr Does it work for you? I would merge it then.

**Comment by ruehr** [comment]
Yes, looks good to me.

Alexander Fabisch <notifications@github.com> schrieb am Fr., 15. Mai 2020,
08:57:
