### ISSUE TITLE
Increase tolerance threshold for matrix check

### ISSUE THREAD

**Issue by theRealSuperMario** [rock-learning/pytransform3d#54]
Hi, I would like to use your library for my project but I get a value error in the line below.

I am pretty sure that my matrix is correct as it represents the extrinsics of a camera.
When I increase the a-tol value `np.allclose`, it works just fine

![image](https://user-images.githubusercontent.com/6517465/85123514-b0086e80-b228-11ea-965d-e94d51de9868.png)

So my suggestion would be to:
1. change the raise to a warning so that one can keep working without hacking around in the library
2. consider pulling up an a-tol flag to every call of the method. However, this would be a pretty large rafactoring.
3. Alternatively, one could try to find a context manager that switches the precision of `np.allclose`, however, I was not able to find this.

https://github.com/rock-learning/pytransform3d/blob/f4c5c01132df31c0c81962ee3857e670ff026699/pytransform3d/rotations.py#L251

I am happy to hear back on suggestions. Apart from that, I think the library is pretty nice to work with and goes well with http://matthew-brett.github.io/transforms3d/

**Comment by theRealSuperMario** [comment]
I added a possible fix here:

https://github.com/theRealSuperMario/pytransform3d/tree/numerical_precision

I could make a PR if desired

**Comment by AlexanderFabisch** [comment]
Hi,

thanks for the feedback. I would need more information.

* I assume the rotation matrix was not computed in pytransform3d. How did you obtain it?
* Can you tell me the exact values to reproduce the error?
* The second check (for the determinant) was introduced only recently. Did you have problems with that?

I agree that raising an error every time something is slightly incorrect is not the most convenient behavior. Numpy has a global function to define error handling: [numpy.seterr](https://numpy.org/doc/stable/reference/generated/numpy.seterr.html). Maybe pytransform3d should have something similar. In addition, I could raise the error threshold a bit, but I'd like to see the exact numbers first.

> I think the library is pretty nice to work with

Good to hear that!

**Comment by theRealSuperMario** [comment]
1. It is from a public dataset (human36M)
2. 
```
0:array([-9.15361835e-01,  4.01808328e-01,  2.57475872e-02, -3.46050839e+02])
1:array([ 5.15480570e-02,  1.80374088e-01, -9.82246499e-01,  5.46980731e+02])
2:array([-3.99318925e-01, -8.97783496e-01, -1.85819250e-01,  5.47448099e+03])
```
Only the [:3,:3] slice is rotation

3. The determinant was not a problem

4. np.seterr was exactly what I was looking for. Thx

**Comment by AlexanderFabisch** [comment]
OK, there is the simple solution in #56. I noticed that assert_rotation_matrix uses another threshold for the test (1e-6). I'm OK with that then. Does it work for you?

**Comment by theRealSuperMario** [comment]
1e-6 worked for me.

However, I still strongly argue that a functionality to just go over the value error should be implemented. 
I have a different matrix case where I calculate the rotation from matrix from a bunch of cross products and the absolute error is very large. However, it still works sufficiently well for my problem, but the ValueError prevents me from using the library.

**Comment by theRealSuperMario** [comment]
Can we merge #56 ? Or do we need more checks?

**Comment by AlexanderFabisch** [comment]
I don't like global variables and I would like to keep the default behavior of rasing errors for numerically unstable rotation matrices. I implemented something similar to your suggestion (2). See #57. Does it work for you?

**Comment by theRealSuperMario** [comment]
Unfortunately not.

I had a look and the entry points for my code are through `check_transform`, which gets called many times within the library

`transform_manager.TransformManager.add_transform`
https://github.com/rock-learning/pytransform3d/blob/b53c8c1e24b88deae1d7c90cafb394da8d26e155/pytransform3d/transform_manager.py#L67

For instance, here the `check_transform` function still calls `check_matrix` without `strict_check`.

When fixing this, you actually have to pass through the `strict_check` flag through many layers, which is kind of ugly. I think there has to be a better way.
I implemented this here : https://github.com/theRealSuperMario/pytransform3d/tree/deactivate_checks

One option would be to put the functions in `transformations.py` into a class (make them methods of that class) and the class takes the `strict_checks` flag during initialization.

**Comment by AlexanderFabisch** [comment]
> When fixing this, you actually have to pass through the `strict_check` flag through many layers, which is kind of ugly. I think there has to be a better way.

I did that now.

>  I implemented this here : https://github.com/theRealSuperMario/pytransform3d/tree/deactivate_checks

If you want to be able to override class-wide `strict_check` in each method call, can you make a pull request based on #57? It would need more documentation (docstring updates) and testing though.

> One option would be to put the functions in `transformations.py` into a class (make them methods of that class) and the class takes the `strict_checks` flag during initialization.

That would change the interface significantly and wouldn't be backward compatible.

**Comment by theRealSuperMario** [comment]
I think it is fine as it is now. Thanks for helping out.
