### ISSUE TITLE
A2B or in fact B2A?

### ISSUE THREAD

**Issue by wagenaartje** [rock-learning/pytransform3d#59]
I am a bit confused about the output of the `transform_from` function. Consider the following snippet

```python
import numpy as np
import matplotlib.pyplot as plt
import pytransform3d.transformations as pt
from pytransform3d.transform_manager import TransformManager

A = np.array([0.0, 0.0, 0.0, 1.0])
A2B = pt.transform_from(np.identity(3), np.array([0.0, 0.0, 1.0]))


tm = TransformManager()
tm.add_transform("A", "B", A2B)

ax = tm.plot_frames_in("A", s=0.1)
ax.set_xlim((-1, 1))
ax.set_ylim((-1, 1))
ax.set_zlim((0.0, 2.0))
plt.show()
``` 

Since I specify that frame B has translation `(x,y,z) = (0,0,1)` compared to frame A, I expect frame B to be above frame A. But when I plot the transformation using the transformation manager, I see that B is in fact below A. Is there something I am not understanding?

![](https://i.imgur.com/1j2nDvf.png)

**Comment by AlexanderFabisch** [comment]
Hi, read the documentation on this issue: https://rock-learning.github.io/pytransform3d/transformation_ambiguities.html#source-in-target-vs-source-to-target

and the docstring should help you to understand what is happening here:

```
add_transform(self, from_frame, to_frame, A2B)
    Register a transform.
    
    Parameters
    ----------
    from_frame : str
        Name of the frame for which the transform is added in the to_frame
        coordinate system
    
    to_frame : str
        Name of the frame in which the transform is defined
    
    A2B : array-like, shape (4, 4)
        Homogeneous matrix that represents the transform from 'from_frame'
        to 'to_frame'
    
    Returns
    -------
    self : TransformManager
        This object for chaining
```

I admit the naming of the arguments should be reconsidered. Maybe it should be `source_frame` and `target_frame`.

**Comment by wagenaartje** [comment]
Thanks for your help, so how should I change the code above so that B appears above A and the variable names still make sense? Because renaming `A2B` to `B2A` would make most sense to me, but still seems incorrect since I supply the position of `B` in `A`.

**Comment by AlexanderFabisch** [comment]
I actually usually use it like that: B2A means "frame B with respect to frame A" to me. Just make sure that everybody who reads the code understands what it means. For example, camera2world means camera frame in world coordinate system. See [here](https://github.com/rock-learning/pytransform3d/blob/master/examples/plot_transform_manager.py). This is also consistent with the docstring of the TransformManager.

**Comment by wagenaartje** [comment]
That clears it up. I was thinking along the lines of `A2B = (from A, to B) = B with respect to A`. So in fact it is `A2B = A with respect to B`, thanks again!
