### ISSUE TITLE
Publish pytransform on PyPI

### ISSUE THREAD

**Issue by AlexanderFabisch** [rock-learning/pytransform3d#7]
There is already a package called pytransform: https://pypi.org/project/pytransform/, so we should rename this package. Possible names:

* pytransform3d
* transform3d

(https://packaging.python.org/tutorials/packaging-projects/)

**Comment by HWiese1980** [comment]
- pytransf
- pytform
- pytransformations

**Comment by AlexanderFabisch** [comment]
https://pypi.org/project/pytransform3d/
