### ISSUE TITLE
How to set convex_hull=false for load_urdf

### ISSUE THREAD

**Issue by grotli** [rock-learning/pytransform3d#92]
When using the plot_mesh function there is a parameter called "convex_hull" that can be set to True/False (which appears to be False by default):
`ax = plot_mesh(filename=os.path.join(data_dir, "my_mesh.stl"), convex_hull=False)`

When using the transformation manager to load an urdf I get the convex hull by default:
`with open(BASE_DIR + "urdf/my_urdf.urdf", "r") as f:
  tm.load_urdf(f.read(), mesh_path=BASE_DIR+"meshes/")`
Is there a way to set the convex_hull parameter when loading the mesh through a urdf-file?

**Comment by AlexanderFabisch** [comment]
No, currently not. I just changed this recently because plotting was quite slow for large meshes and I was waiting for someone to complain about it. :) Give me a couple of minutes to introduce a parameter to control this.

**Comment by AlexanderFabisch** [comment]
#93 adds some options to control the output. Could you check if it works for your case?

**Comment by AlexanderFabisch** [comment]
@grotli Did you read my reply?

**Comment by grotli** [comment]
Yes! That worked very well, thank you! :-) 
Just a minor comment: "convex_hull" is the parameter name in the "plot_mesh" function, where as "convex_hull_of_mesh" is the parameter name in the "plot_visuals" function in the TransformationManager class.

**Comment by AlexanderFabisch** [comment]
Yes, I thought it would be better to give it a more precise name in the TransformManager since it does not make sense to compute the convex hull of a sphere, box, or cylinder. In `plot_mesh` it should be quite obvious that it is the convex hull of the mesh. Does it make sense?

**Comment by grotli** [comment]
Yes, that makes sense.

**Comment by AlexanderFabisch** [comment]
OK, thanks. I will merge it to master in a minute.
